

using System.Collections.Generic;

namespace TheRetailStoreDiscounts.ClassLib
{
    /// <summary>
    /// The class Bill models the concept of a bill generated by the retail website 
    /// for items bought an object of User
    /// </summary>//     

    public class Bill
    {
        List <Item> items = null;
        public Bill (List<Item>items)
        {
            this.items = new List<Item>();
            this.items = items;  
        }
    }
}
