

using System.Collections.Generic;

namespace TheRetailStoreDiscounts.ClassLib
{
    /// <summary>
    /// The class Bill models the concept of a bill generated by the retail website 
    /// for items bought an object of User
    /// </summary>//     

    public class Bill
    {
        private int billNumber;
        private double amount = 0.0;
        private string itemDescription = string.Empty;

        public Bill (int billNumber, double amount, string itemDescription)
        {
            this.billNumber = billNumber;
            this.amount = amount;
            this.itemDescription = itemDescription;
        }

        public double getAmount() => amount;
        public string getItem(){ return itemDescription;}
    }
}
